language: java
jdk:
  - openjdk11
# 어느 브랜치에 푸시될때 수행할건지
branches:
  only:
    - master
before_install:
  - chmod +x gradlew

# Travis CI 서버의 home
# gradle 의존을 받게되면 캐시하여 , 같은 의존은 안받음
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시될때 수행하는 명령어
# gradlew clean, build 를 수행행
script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - wnsgur765z@gmail.com
# jar 파일은인식하지 못하므로 jar 파일들을 모아 압축한다
before_deploy:
  - zip -r simso * # 자신의 프로젝트 이름
  - mkdir -p deploy # Travis CI가 실행중인 위치
  - mv simso.zip deploy/simso.zip
# S3 파일 업로드 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선언
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECCRET_KEY

    bucket: freelec-springboot-build3 # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리로 이동한다. 해당 위치의 파일만 이동시킨다.
    wait-until-deployed: true