language: java
jdk:
  - openjdk11
# 어느 브랜치에 푸시될때 수행할건지
branches:
  only:
    - master

# Travis CI 서버의 home
# gradle 의존을 받게되면 캐시하여 , 같은 의존은 안받음
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시될때 수행하는 명령어
# gradlew clean, build 를 수행행
cript: "./gradlew clean build"