spring:
  profiles:
    include: oauth, real-db
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  session:
    store-type: jdbc
    jdbc.initialize-schema: always # 테이블 자동생성