spring:
  profiles:
    include: oauth

  datasource:
    url: jdbc:h2:tcp://localhost/~/hello;
    username: sa
    password: 1
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  session:
    store-type: jdbc
    jdbc.initialize-schema: always # 테이블 자동생성
logging:
  level:
    org.hibernate.SQL: debug
  #  org.hibernate.type: trace